#!/bin/zsh
typeset -gA map
map[root/key1]='<$name>$subnode</$name>'
map[root/key1/@name]='one'
map[root/key1/@title]='zhoujiabo'
map[root/key1/a]='<$name>[$title]</$name>'
map[root/key1/a/@name]='Apple'
map[root/key1/b]='<$name></$name>'
map[root/key1/b/@name]='Brain'
map[root/key1/c]='<$name></$name>'
map[root/key1/c/d]='<$name>...</$name>'
map[root/key1/c/d/@name]='垃圾'
map[root/key1/c/@name]='c'



function instance() {
    function keyset() {
        for x in ${(k)map}; do
            [[ "$(basename $x)" == @* ]] || echo $x 
        done
    }

    function attrs() {
        local key=$1
        for x in ${(k)map}; do
            [[ $(basename $x) == @* ]] && [[ $(dirname $x) == $key ]] && {
                echo $x
            }
        done
    }


    local key=$1
    [[ "$(basename $key)" == @* ]] && return
    local subnode

    # expose attrs
    for attr in $(attrs $key); do
        local ${$(basename $attr)#@}=$map[$attr]
    done

    # instance direct child node 
    for x in $(keyset); do
        [[ $(dirname $x) == $key ]] && {
            subnode+=$(instance $x)
        }
    done

    echo ${(e)map[$key]}
}

instance root/key1
