#!/bin/zsh

function main() {

    local home=.
    local result
    result=$(lint --check UnusedResources $home)
    #result=$(</tmp/unuse.txt)
    
    d "检测无用的: 颜色"
    <<< $result | unused_colors    > $out/unused_colors.log

    d "检测无用的: 字符串"  
    <<< $result | unused_strings   > $out/unused_strings.log

    d "检测无用的: 图片"    
    <<< $result | unused_drawables > $out/unused_drawables.log

    d "检测无用的: 数组"    
    <<< $result | unused_arraies   > $out/unused_arraies.log

    d "检测无用的: 布局文件"    
    <<< $result | unused_layouts   > $out/unused_layouts.log
}

function unused_layouts() {
    sed -e 's/.*\(res\/layout[a-Z_0-9\-]*\/[a-Z]\w*.\w*[.]\w*\).*:\ .*\ .*/\1/g;t_;d;:_'
}

function unused_strings() {
    sed -e 's/.*<string name="\([a-Z][a-Z_0-9]*\)".*/\1/g;t_;d;:_' 
}

function unused_arraies() {
    sed -e 's/.*<\w*-array name="\([a-Z][a-Z_0-9]*\)".*/\1/g;t_;d;:_' 
}

function unused_colors() {
    sed -e 's/.*<color name="\(.*\)".*/\1/g;t_;d;:_' 
}

function unused_drawables() {
    sed -e 's/.*\(res\/drawable[a-Z_0-9\-]*\/[a-Z]\w*.\w*[.]\w*\).*:\ .*\ .*/\1/g;t_;d;:_'
}

function d() {
    echo "$*"
}

out=.unused
[[ -d $out ]] || mkdir $out
main "$@"
