#!/bin/zsh



# $1 : expect length
# $2 : the string to repeat
function fill() {
    repeat $1; print -n $2
}

# Create screen buffer
# $1: height
# $2: width
function screen.create() {
    local h=$1
    local w=$2
    local l=$(fill w " ")
    repeat h; print $l
}

# calc text dim (height width)
# $1: var name
function screen.dim() {
    local name=$1
    local w t
    t=${(t)${(P)name}}
    [[ $t == scalar ]] && {
        print 1 ${#${(P)name}}
        return
    }

    for x in ${(P)name}; do
        w=$(( $#x > w ? $#x : w));
    done
    print ${#${(P)name}} $w 
}

function max() {
    print -n $(( $1 > $2 ? $1 : $2))
}

# $1 : screen buffer
# $2 : top
# $3 : left
# $4 : draw object
# SCREEN::array
# WIDTH::int 
# HEIGHT::int
function screen.draw() {
    local -a obj
    obj=("${(@f)3}")
    local top=$1
    local left=$2

    integer i=1 width=0
    for o in "${(@)obj}"; do
        line=$SCREEN[i+top]
        SCREEN[i+top]="$line[1,left]${o}${line[$#o+left+1,-1]}"
        i=i+1
        width=$(max $#o width)
    done
    
    # set external var
    HEIGHT=$#obj
    WIDTH=$width
    MAX_HEIGHT=$(max MAX_HEIGHT $#obj)
}

function screen.inline() {
    local SCREEN=("${(@f)$(screen.create 20 150)}")
    local HEIGHT=0 WIDTH=0 MAX_HEIGHT
    local -i top left
    for elem in $argv; do
        screen.draw $top $left "${elem}"
        left+=$WIDTH
    done

    print -l $SCREEN[1,MAX_HEIGHT]
}

a="
|1 2 3 9|
|4 5 6 1|
|4 5 6 1|
|4 5 6 1|
|4 5 6 1|
|4 5 6 1|
|4 5 6 1|
"
b="
┃1 2  3 9┃
┃4 5 6 1┃
" 
plus="
 + 
"
screen.inline "$a" "${plus}" "$b" "${plus}" "$b"


function matrix() {
    local name=$1
    local -a data=(${(f)2})
    local -a xs
    local -i m n
    m=$#data
    for x in $data; do
        xs+=(${(s: :)x})
    done
    n=$(( $#xs / m ))
    set -A $name "@matrix:$m:$n" $xs[@]
}

function matrix.toString() {
    local -a head=(${(s=:=)${${(P)1}[1]}};)
    [[ $head[1] == @matrix ]] || exit -1
    local -i m=$head[2] n=$head[3]
    local -a data=(${${(P)1}[2,-1]})
    for ((i=0; i<m; ++i)) {
        print $data[i*n+1,i*n+n]
    }
}

# mmulti 1 2 3 4 = 1*2 + 3*4
function mmulti() {
    local -i r
    for ((i=1; i<$#argv; ++i)); do
        r+=$(($argv[i]*argv[i+$#argv/2]))
    done
    print $r
}

function matrix.multi() {
    local ma=$1 mb=$2
    local -a _a _b
    _a=(${(P)ma})
    _b=(${(P)mb})
    ha=(${(s=:=)$_a[1]})
    hb=(${(s=:=)$_b[1]})

    local -i am an bm bn
    am=ha[2]
    an=ha[3]

    bm=hb[2]
    bn=hb[3]

    [[ an != bm ]] && {
        return
    }
    for ((i=1; i<am; ++i)); do
       multi $a[i] 
    done
}

function matrix.row() {
    local name=$1

}

function matrix.add() {

}

matrix M1 "
1 1 1
2 2 2
3 3 3
"

matrix M2 "
2
2
"

#matrix.toString M1
#matrix.toString M2

mmulti 2 1 2 2
