#!/bin/zsh
# @author: amas
# @email : zhoujb.cn@gmail.com
# @desc  : backup the trac env

function help() {
    local DESC="\
The help message!!!
"
    [[ -n $1 ]] && print -u2 "$1"
    print -u2 $DESC
    return $2 
}

function backend_git() {
    local repo=$1
    [[ -d $repo ]] && {
        (
            cd $repo
            git add -A
            git commit -am "tracbackup auto backup @$(date +%Y%d%m:%H%M%S)"
            git pull origin master
            git push origin master
        )
    }
}

function backend_ssh() {

}

function wiki_export() {
    local tracenv=$1
    local dir=$2

    mkdir -p $dir 2> /dev/null
    rm $dir/*
    trac-admin "$tracenv" wiki dump "$dir" && return 0
    return 1
}

function main() {
    local tracenv home
    typeset opts
    local -a flags

    [[ -z $argv ]] && return $(help "" 1)
    zparseopts -A opts -K -D -E -- -t:=opts
    tracenv=$1
    home=$2

    wiki_export "$tracenv" "$home"
    backend_git "$home"
}

main $*

