#!/bin/zsh

zmodload zsh/datetime


function date.epoch() {
    local -i offset=${1:=0}
    local fmt="%s"
    local now=$(strftime "%Y-%m-%d" $epochtime[1])
    local -i time
    strftime -r -s time "%Y-%m-%d" $now

    time=$((time + $offset*24*60*60))
    strftime "$fmt" $time
    print hello
}

function date.ns() {
    local -i offset=${1:=0}
    local fmt=${2:=%Y-%m-%d}
    local now=$(strftime "%Y-%m-%d" $epochtime[1])
    local -i time
    strftime -r -s time "%Y-%m-%d" $now

    time=$((time + $offset*24*60*60))
    strftime "$fmt" $time
}
