#!/bin/zsh
#
# @matrix header=a:b:c:d
TEST_MATRIX='
[NAMES]
NAME AGE SEX
amas 19
wang 这个

[MENUS]
ID TITLE DESC
delete "add nihao"
add    delete 这个
'
# MAGIC HEADER(F1:F2:...:Fn) DIM(MxN)
MATRIX_MAGIC=@MATRIX

function main() {
    local content="$(<&0)"
    # local content=$TEST_MATRIX
   
    local fsep='\n'
    local lsep="\n"
    local -a contents
    local -a header
    contents=(${(f)content})

    local matrix_name
    local -a matrix_contents
    local -a matrix_header

    function read_matrix() {
        local vname=${${(s=::=)section_name}[1]}
        local vtype=${${(s=::=)section_name}[2]} 

        local line
        [[ $vtype == map ]] && {
            typeset -gA $vname
            for line in $matrix_contents;do
                #TODO    
            done
        }

        local -a xs
        typeset -ga $vname
        matrix_header=(${(s: :)matrix_contents[1]})
        local -i len=$#matrix_header 
        

        set -A $vname $MATRIX_MAGIC $len $matrix_header
        for line in $matrix_contents[2,-1];do
            xs=(${(z)line})
            repeat $((len-$#xs)) { xs+= }
            set -A $vname "${(@P)vname}" "${(@)xs}"
        done

       
        reset
    }

    function reset() {
        matrix_contents=()
        section_name=
        section_type= 
    }

    function print_matrix() {
        local _name=$1
        local _col=${${(P)_name}[2]}
        typeset -p $_name
        eval "print -aC $_col "'"${(@)'$_name"[3,-1]}\""
        # 上面这个太难懂了,参考下面这句
        #print -aC $matrix "${(@)matrix[3,-1]}"
    }

    for line in $contents; do
        # skip comment
        [[ $line =~ '^#.*' ]] && continue
        if [[ $line =~ '\[([a-Z_:]+)\]' ]]; then
            [[ -n $matrix_contents ]] && {
                read_matrix
            }

            # NAME::TYPE
            section_name=$match[1]
        else
           [[ -n $section_name ]] && {
               matrix_contents+=$line
           }
        fi
    done

    [[ -n $matrix_contents ]] && {
        read_matrix
    }
}

function ismatrix() {
    local vname=$1
    [[ ${(tP)vname} == array ]] && [[ ${${(P)vname}[1]} == $MATRIX_MAGIC ]] && (( ${(P)#vname} >= 3 )) && return 0
    return 1
}

main $*
