#!/bin/zsh
MATRIX_MAGIC=@MATRIX
function ismatrix() {
    local vname=$1
    [[ ${(tP)vname} == array ]] && [[ ${${(P)vname}[1]} == $MATRIX_MAGIC ]] && (( ${(P)#vname} >= 3 )) && return 0
    return 1
}

local mname=$1
[[ -z $mname ]] && return 1 

ismatrix $mname || return 1

local header_len=${${(P)mname}[2]}
local -a xs
local header=
header=${${(P)mname}[3,3+$header_len-1]}
xs=("${(@P)mname}")
@emap -c $header -- "${(@)xs[3+$header_len,-1]}"
