#!/bin/zsh
# xargs 可以向指定函数反复提交多个参数, 
# @emap '$1 "This is not mine" ' -- {1..999} | @xargs '(){ echo $2 $1}' 
# 将所有目录打包
# print -l * | @pipeline '(){ tar czvf $1.tgz $1}'
# 支持\0分割？？？
# FIXME:
# echo "()" | @xargs  -> will case eval error
function main() {
    (
        help() {
            [[ -n $argv ]] && print $argv
            print -- "\
$ print -l {1..10} | @xargs echo
OPTIONS
    -s <seperator> : How to splite input
    -0             : splite with '\0', same with -s $'\0'
"
        }

        local -a _argv _o_splite _o_flags

        seperator=(-s $'\n')
        
        zparseopts -D -K -- s:=seperator 0=_o_flags
        [[ -z $argv ]] && help "no functions or command" && return -1
        [[ -n $_o_flags[(r)-0] ]] && seperator=(-s $'\0')


        IFS="$seperator[2]"
        _argv=("${=$(<&0)}")

        for x in $_argv; do
            $argv ${(Q)${(z)x}}
        done
    )
}

main $*
