#!/bin/zsh
# f命令负责将内容放置到磁盘上
(
setopt EXTENDED_GLOB
local -A map
local store_spec target

function writer.stdout() {
    <<< ${(F)content}
}

function writer.file() {
    # TODO: append writer support ???
    local file="$1"
    [[ $file == @stdout ]] && <<< ${(F)content} &&  content=() && return
    [[ -z $content ]] && @EF "没有输出内容" && return
    [[ -z $file    ]] && @EF "没有输出文件" && return
    local parent=$(dirname $file)

    # ensure the directory existed
    [[ -d $parent ]] || mkdir -p "$parent"
    <<< ${(F)content} > "$file"
    content=()
}

#--------------------------------------------------------------------[ body ]
type=file
local -a content
for _line in "${(@f)$(<&0)}"; do
    # @IF $_line
    if [[ $_line = (#b)\====(=)#\|(\ )#(*) ]]; then
        writer.$type ${target%%(\ )#}
        # store_spec=$match[3]
        target=$match[3]
        continue
    fi
    content+="$_line"
done

writer.$type ${target%%(\ )#}
# TODO 检测结果
)
