#!/bin/zsh

function main() {
    help() {
        echo "updateElement xpath [-value value] [attr1=value1 attr2=value2 ... attrN=valueN]"
        echo "No Docs!"
    }
    [[ $# < 1 ]] && help && return -1
    local xpath="$1" ; shift
    local skipValue=$argv[(r)-value]

    local opts
    zparseopts -A opts -K -D -E  -- value:=opts
    
    local xml=
    local elementValue=$opts[-value]
    xml=$(<&0)
    
    [[ -z $xml ]] && return 0

    local name value options
    if [[ -n $skipValue ]]; then
        options+=" -u \"$xpath\" -v \"$elementValue\""
    fi

    # TODO(amas): use s:=: replace it
    setopt EXTENDED_GLOB
    for x in $argv; do 
       if [[ $x = (#b)(*)=(*) ]]; then
           name=$match[1]
           value=$match[2]  
           options+=" -d \"$xpath/@$name\" -s \"$xpath\" -t attr -n \"$name\"  -v \"$value\""
       fi
    done
    unsetopt EXTENDED_GLOB
    eval "echo \$xml | xml ed $options"
}

main $*
